version: "2"
prepare:
  fetch:
    - url: http://engineering.pages.bytemark.co.uk/dev-utilities/.rubocop.yml
      path: .rubocop-http---engineering-pages-bytemark-co-uk-dev-utilities--rubocop-yml
    - url: http://engineering.pages.bytemark.co.uk/dev-utilities/.rubocop-rails.yml
      path: .rubocop-http---engineering-pages-bytemark-co-uk-dev-utilities--rubocop-rails-yml
plugins:
  #brakeman: # brakeman doesn't work outside of rails apps.
    #enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint: 
    enabled: true
  eslint: 
    enabled: true
  gofmt: 
    enabled: true
  golint: 
    enabled: true
  govet: 
    enabled: true
  nodesecurity: 
    enabled: true
  pep8: 
    enabled: true
  phpcodesniffer: 
    enabled: true
  phpmd: 
    enabled: true
  rubocop:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - .bundle/
  - vendor/
