engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Metrics/LineLength:
        enabled: false
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
ratings:
   paths:
   - lib/**
   - "**.rb"
exclude_paths:
- bin/**/*
- spec/**/*
- coverage/**/*
