stages:
  - test
  - package
  - publish

codeclimate:
  image: $CI_REGISTRY/docker-images/layers:stretch-codeclimate
  stage: test
  tags:
    - docker-socket
  script:
    - codeclimate
  variables:
    CODECLIMATE_DEBUG: "1"
  artifacts:
    paths: [codeclimate.json]

test:
  stage: test
  image: $CI_REGISTRY/docker-images/layers:stretch-ruby
  coverage: '/\(\d+.\d+\%\) covered/'
  before_script:
    - apt install -y zlib1g-dev
  script:
    - gem install bundler
    - bundle install --path vendor/bundle -j $(nproc)
    - bundle exec rspec

package:
  stage: package
  image: $CI_REGISTRY/docker-images/layers:stretch-ruby
  variables:
    GEMFILE: decanter.gemspec
  artifacts:
    paths:
      - pkg
  script:
    - package

publish:
  stage: publish
  tags:
    - shell
  script:
    - publish
