AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'decanter.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'decanter.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 205

Metrics/AbcSize:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: single_quotes 